// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/demo16/dao/internal"
)

// demoGen16Dao is the data access object for the table demo_gen16.
// You can define custom methods on it to extend its functionality as needed.
type demoGen16Dao struct {
	*internal.DemoGen16Dao
}

var (
	// DemoGen16 is a globally accessible object for table demo_gen16 operations.
	DemoGen16 = demoGen16Dao{internal.NewDemoGen16Dao()}
)

// Add your custom methods and functionality below.
