// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/demo16/dao/internal"
)

// demoGenClass16Dao is the data access object for the table demo_gen_class16.
// You can define custom methods on it to extend its functionality as needed.
type demoGenClass16Dao struct {
	*internal.DemoGenClass16Dao
}

var (
	// DemoGenClass16 is a globally accessible object for table demo_gen_class16 operations.
	DemoGenClass16 = demoGenClass16Dao{internal.NewDemoGenClass16Dao()}
)

// Add your custom methods and functionality below.
