// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUserOnline is the golang structure for table sys_user_online.
type SysUserOnline struct {
	Id         uint64      `json:"id"         description:""`
	Uuid       string      `json:"uuid"       description:"user id"`
	Token      string      `json:"token"      description:"usertoken"`
	CreateTime *gtime.Time `json:"createTime" description:"description:"login time"`
	UserName   string      `json:"userName"   description:"user name"`
	Ip         string      `json:"ip"         description:"loginip"`
	Explorer   string      `json:"explorer"   description:"browser"`
	Os         string      `json:"os"         description:"operating system"`
}
