// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-08 11:31:48
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysLoginLog is the golang structure for table sys_login_log.
type SysLoginLog struct {
	InfoId        int64       `json:"infoId"        description:"AccessID"`
	LoginName     string      `json:"loginName"     description:"Login account"`
	Ipaddr        string      `json:"ipaddr"        description:"LoginIPaddress"`
	LoginLocation string      `json:"loginLocation" description:"Login location"`
	Browser       string      `json:"browser"       description:"Browser type"`
	Os            string      `json:"os"            description:"Operating system"`
	Status        int         `json:"status"        description:"Login status（0success 1failure）"`
	Msg           string      `json:"msg"           description:"Prompt message"`
	LoginTime     *gtime.Time `json:"loginTime"     description:"Login time"`
	Module        string      `json:"module"        description:"Login module"`
}
