// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-07 23:26:21
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPost is the golang structure for table sys_post.
type SysPost struct {
	PostId    uint64      `json:"postId"    description:"PostID"`
	PostCode  string      `json:"postCode"  description:"Post Code"`
	PostName  string      `json:"postName"  description:"Post Name"`
	PostSort  int         `json:"postSort"  description:"Display Order"`
	Status    uint        `json:"status"    description:"Status（0Normal 1Disabled）"`
	Remark    string      `json:"remark"    description:"Remark"`
	CreatedBy uint64      `json:"createdBy" description:"Creator"`
	UpdatedBy uint64      `json:"updatedBy" description:"Modifier"`
	CreatedAt *gtime.Time `json:"createdAt" description:"Creation Time"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"Modification Time"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"Deleted at"`
}
