// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysUserPost is the golang structure for table sys_user_post.
type SysUserPost struct {
	UserId int64 `json:"userId" description:"UserID"`
	PostId int64 `json:"postId" description:"PostID"`
}
