// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysOperLog is the golang structure for table sys_oper_log.
type SysOperLog struct {
	OperId        uint64      `json:"operId"        description:"Log primary key"`
	Title         string      `json:"title"         description:"Module title"`
	BusinessType  int         `json:"businessType"  description:"Business type（0other 1add 2modify 3delete）"`
	Method        string      `json:"method"        description:"Method name"`
	RequestMethod string      `json:"requestMethod" description:"Request method"`
	OperatorType  int         `json:"operatorType"  description:"Operation category（0other 1backend user 2mobile user）"`
	OperName      string      `json:"operName"      description:"Operator"`
	DeptName      string      `json:"deptName"      description:"Department name"`
	OperUrl       string      `json:"operUrl"       description:"RequestURL"`
	OperIp        string      `json:"operIp"        description:"Host address"`
	OperLocation  string      `json:"operLocation"  description:"Operation location"`
	OperParam     string      `json:"operParam"     description:"Request parameter"`
	ErrorMsg      string      `json:"errorMsg"      description:"Error message"`
	OperTime      *gtime.Time `json:"operTime"      description:"Operation time"`
}
