// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysAuthRule is the golang structure for table sys_auth_rule.
type SysAuthRule struct {
	Id         uint        `json:"id"         description:""`
	Pid        uint        `json:"pid"        description:"ParentID"`
	Name       string      `json:"name"       description:"Rule name"`
	Title      string      `json:"title"      description:"Rule name"`
	Icon       string      `json:"icon"       description:"icon"`
	Condition  string      `json:"condition"  description:"condition"`
	Remark     string      `json:"remark"     description:"Remark"`
	MenuType   uint        `json:"menuType"   description:"Type 0Directory 1Menu 2Button"`
	Weigh      int         `json:"weigh"      description:"Weight"`
	IsHide     uint        `json:"isHide"     description:"Display status"`
	Path       string      `json:"path"       description:"Route address"`
	Component  string      `json:"component"  description:"component path"`
	IsLink     uint        `json:"isLink"     description:"Is it an external link 1yes 0no"`
	ModuleType string      `json:"moduleType" description:"module"`
	ModelId    uint        `json:"modelId"    description:"modelID"`
	IsIframe   uint        `json:"isIframe"   description:"Is it embedded in iframe"`
	IsCached   uint        `json:"isCached"   description:"Is it cached"`
	Redirect   string      `json:"redirect"   description:"route redirect address"`
	IsAffix    uint        `json:"isAffix"    description:"Is it fixed"`
	LinkUrl    string      `json:"linkUrl"    description:"link address"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:"creation date"`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:"modification date"`
}
