// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDept is the golang structure for table sys_dept.
type SysDept struct {
	DeptId    uint64      `json:"deptId"    description:"Department id"`
	ParentId  uint64      `json:"parentId"  description:"Parent department id"`
	Ancestors string      `json:"ancestors" description:"Ancestor list"`
	DeptName  string      `json:"deptName"  description:"Department name"`
	OrderNum  int         `json:"orderNum"  description:"Display order"`
	Leader    string      `json:"leader"    description:"Manager"`
	Phone     string      `json:"phone"     description:"Phone number"`
	Email     string      `json:"email"     description:"Email"`
	Status    uint        `json:"status"    description:"Department status（0normal 1disabled）"`
	CreatedBy uint64      `json:"createdBy" description:"Creator"`
	UpdatedBy int64       `json:"updatedBy" description:"Modifier"`
	CreatedAt *gtime.Time `json:"createdAt" description:"Creation time"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"Modification time"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"Deletion time"`
}
