// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-02 16:48:23
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	Id            uint64      `json:"id"            description:""`
	UserName      string      `json:"userName"      description:"User name"`
	Mobile        string      `json:"mobile"        description:"Chinese mobile phones do not have country codes，The format of international mobile phone numbers is：country code-mobile number"`
	UserNickname  string      `json:"userNickname"  description:"User nickname"`
	Birthday      int         `json:"birthday"      description:"Birthday"`
	UserPassword  string      `json:"userPassword"  description:"Login password;cmf_password encryption"`
	UserSalt      string      `json:"userSalt"      description:"Encryption salt"`
	UserStatus    uint        `json:"userStatus"    description:"User status;0:disabled,1:normal,2:unverified"`
	UserEmail     string      `json:"userEmail"     description:"User login email"`
	Sex           int         `json:"sex"           description:"Gender;0:Confidential,1:Male,2:Female"`
	Avatar        string      `json:"avatar"        description:"User avatar"`
	DeptId        uint64      `json:"deptId"        description:"Departmentid"`
	Remark        string      `json:"remark"        description:"Remark"`
	IsAdmin       int         `json:"isAdmin"       description:"Whether it is the backend administrator 1 Yes  0   No"`
	Address       string      `json:"address"       description:"Contact address"`
	Describe      string      `json:"describe"      description:"Description information"`
	LastLoginIp   string      `json:"lastLoginIp"   description:"Last login ip"`
	LastLoginTime *gtime.Time `json:"lastLoginTime" description:"Last login time"`
	CreatedAt     *gtime.Time `json:"createdAt"     description:"Creation time"`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:"Update time"`
	DeletedAt     *gtime.Time `json:"deletedAt"     description:"Deleted At"`
}
