// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysRole is the golang structure for table sys_role.
type SysRole struct {
	Id        uint        `json:"id"        description:""`
	Status    uint        `json:"status"    description:"Status;0:disabled;1:normal"`
	ListOrder uint        `json:"listOrder" description:"sort"`
	Name      string      `json:"name"      description:"Role name"`
	Remark    string      `json:"remark"    description:"remark"`
	DataScope uint        `json:"dataScope" description:"Data scope（1：all data permissions 2：custom data permissions 3：data permissions of this department 4：data permissions of this department and below）"`
	CreatedAt *gtime.Time `json:"createdAt" description:"creation time"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"update time"`
}
