// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-08 11:31:48
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysLoginLog is the golang structure of table sys_login_log for DAO operations like Where/Data.
type SysLoginLog struct {
	g.Meta        `orm:"table:sys_login_log, do:true"`
	InfoId        interface{} // Access ID
	LoginName     interface{} // Login account
	Ipaddr        interface{} // Login IP address
	LoginLocation interface{} // Login location
	Browser       interface{} // Browser type
	Os            interface{} // Operating system
	Status        interface{} // Login status (0 success 1 failure)
	Msg           interface{} // Message message
	LoginTime     *gtime.Time // Login time
	Module        interface{} // Login module
}
