// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysOperLog is the golang structure of table sys_oper_log for DAO operations like Where/Data.
type SysOperLog struct {
	g.Meta        `orm:"table:sys_oper_log, do:true"`
	OperId        interface{} // Log primary key
	Title         interface{} // Module title
	BusinessType  interface{} // Business type (0 Other 1 Add 2 Modify 3 Delete)
	Method        interface{} // Method name
	RequestMethod interface{} // Request method
	OperatorType  interface{} // Operation type (0 Other 1 Backend user 2 Mobile user)
	OperName      interface{} // Operator
	DeptName      interface{} // Department name
	OperUrl       interface{} // RequestURL
	OperIp        interface{} // Host address
	OperLocation  interface{} // Operation location
	OperParam     interface{} // Request parameters
	ErrorMsg      interface{} // Error message
	OperTime      *gtime.Time // Operation time
}
