// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysRole is the golang structure of table sys_role for DAO operations like Where/Data.
type SysRole struct {
	g.Meta    `orm:"table:sys_role, do:true"`
	Id        interface{} //
	Status    interface{} // Status;0:Disabled;1:Normal
	ListOrder interface{} //  Sorting
	Name      interface{} // Role name
	Remark    interface{} // Remark
	DataScope interface{} // Data scope (1: All data permissions 2: Custom data permissions 3: Department data permissions 4: Department data permissions and below)
	CreatedAt *gtime.Time // Creation time
	UpdatedAt *gtime.Time // Update time
}
