// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-02 16:48:23
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
	g.Meta        `orm:"table:sys_user, do:true"`
	Id            interface{} //
	UserName      interface{} // Username
	Mobile        interface{} // Chinese mobile phone numbers do not have country codes. International mobile phone numbers are formatted as: country code - mobile number
	UserNickname  interface{} // User nickname
	Birthday      interface{} // Birthday
	UserPassword  interface{} // Login password; encrypted with cmf_password
	UserSalt      interface{} // Encryption salt
	UserStatus    interface{} //  User status;0:Disabled,1:Normal,2:Unverified
	UserEmail     interface{} // User login email
	Sex           interface{} // Gender;0:Confidential,1:Male,2:Female
	Avatar        interface{} // User avatar
	DeptId        interface{} // Department ID
	Remark        interface{} // Remark
	IsAdmin       interface{} // Is this the administrator? 1: Yes 0: No
	Address       interface{} // Contact address
	Describe      interface{} // Description
	LastLoginIp   interface{} // Last login IP address
	LastLoginTime *gtime.Time // Last login time
	CreatedAt     *gtime.Time // Creation time
	UpdatedAt     *gtime.Time // Update time
	DeletedAt     *gtime.Time // Delete time
}
