// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDept is the golang structure of table sys_dept for DAO operations like Where/Data.
type SysDept struct {
	g.Meta    `orm:"table:sys_dept, do:true"`
	DeptId    interface{} // Department ID
	ParentId  interface{} // Parent department ID
	Ancestors interface{} // Ancestor list
	DeptName  interface{} // Department name
	OrderNum  interface{} // Display order
	Leader    interface{} // Leader
	Phone     interface{} // Contact number
	Email     interface{} // Email address
	Status    interface{} // Department status (0Normal 1Inactive)
	CreatedBy interface{} // Created by
	UpdatedBy interface{} // Modified by
	CreatedAt *gtime.Time // Creation time
	UpdatedAt *gtime.Time // Modification time
	DeletedAt *gtime.Time // Deleted time
}
