// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-07 23:26:21
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPost is the golang structure of table sys_post for DAO operations like Where/Data.
type SysPost struct {
	g.Meta    `orm:"table:sys_post, do:true"`
	PostId    interface{} // Post ID
	PostCode  interface{} // Post code
	PostName  interface{} // Post name
	PostSort  interface{} // Display order
	Status    interface{} // Status (0Normal 1Disabled)
	Remark    interface{} // Remark
	CreatedBy interface{} // Creator
	UpdatedBy interface{} // Modifier
	CreatedAt *gtime.Time // Creation time
	UpdatedAt *gtime.Time // Modification time
	DeletedAt *gtime.Time // Delete time
}
