// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUserOnline is the golang structure of table sys_user_online for DAO operations like Where/Data.
type SysUserOnline struct {
	g.Meta     `orm:"table:sys_user_online, do:true"`
	Id         interface{} //
	Uuid       interface{} // User ID
	Token      interface{} // User token
	CreateTime *gtime.Time // Login time
	UserName   interface{} // User name
	Ip         interface{} // Login IP address
	Explorer   interface{} // Browser
	Os         interface{} // Operating system
}
