// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-16 16:32:52
// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-16 16:32:52
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictData is the golang structure of table sys_dict_data for DAO operations like Where/Data.
type SysDictData struct {
	g.Meta    `orm:"table:sys_dict_data, do:true"`
	DictCode  interface{} // Dictionary code
	DictSort  interface{} // Dictionary sort
	DictLabel interface{} // Dictionary label
	DictValue interface{} // Dictionary key
	DictType  interface{} // Dictionary type
	CssClass  interface{} // Style attributes (other style extensions)
	ListClass interface{} // Table echo style
	IsDefault interface{} // Default (1yes, 0no)
	Status    interface{} // Status (0normal, 1disabled)
	CreateBy  interface{} // Creator
	UpdateBy  interface{} // Updater
	Remark    interface{} // Remark
	CreatedAt *gtime.Time // Creation time
	UpdatedAt *gtime.Time // Modification time
}
