// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-18 21:09:17
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysConfig is the golang structure of table sys_config for DAO operations like Where/Data.
type SysConfig struct {
	g.Meta      `orm:"table:sys_config, do:true"`
	ConfigId    interface{} // Parameter primary key
	ConfigName  interface{} // Parameter name
	ConfigKey   interface{} // Parameter key name
	ConfigValue interface{} // Parameter key value
	ConfigType  interface{} // System built-in (Yyes Nno)
	CreateBy    interface{} // Created by
	UpdateBy    interface{} // Updated by
	Remark      interface{} // Remark
	CreatedAt   *gtime.Time // Creation time
	UpdatedAt   *gtime.Time // Modification time
}
