// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-16 16:32:52
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictType is the golang structure of table sys_dict_type for DAO operations like Where/Data.
type SysDictType struct {
	g.Meta    `orm:"table:sys_dict_type, do:true"`
	DictId    interface{} // Dictionary primary key
	DictName  interface{} // Dictionary name
	DictType  interface{} // Dictionary type
	Status    interface{} // Status (0Normal, 1Disabled)
	CreateBy  interface{} // Creator
	UpdateBy  interface{} // Updater
	Remark    interface{} // Remark
	CreatedAt *gtime.Time // Creation date
	UpdatedAt *gtime.Time // Modification date
}
