// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/demo/dao/internal"
)

// demoGenDao is the data access object for the table demo_gen.
// You can define custom methods on it to extend its functionality as needed.
type demoGenDao struct {
	*internal.DemoGenDao
}

var (
	// DemoGen is a globally accessible object for table demo_gen operations.
	DemoGen = demoGenDao{internal.NewDemoGenDao()}
)

// Add your custom methods and functionality below.
