// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/demo/dao/internal"
)

// demoGenClassDao is the data access object for the table demo_gen_class.
// You can define custom methods on it to extend its functionality as needed.
type demoGenClassDao struct {
	*internal.DemoGenClassDao
}

var (
	// DemoGenClass is a globally accessible object for table demo_gen_class operations.
	DemoGenClass = demoGenClassDao{internal.NewDemoGenClassDao()}
)

// Add your custom methods and functionality below.
