// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/research/dao/internal"
)

// researchWrittenWorksDao is the data access object for the table research_written_works.
// You can define custom methods on it to extend its functionality as needed.
type researchWrittenWorksDao struct {
	*internal.ResearchWrittenWorksDao
}

var (
	// ResearchWrittenWorks is a globally accessible object for table research_written_works operations.
	ResearchWrittenWorks = researchWrittenWorksDao{internal.NewResearchWrittenWorksDao()}
)

// Add your custom methods and functionality below.
