// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/research/dao/internal"
)

// researchDao is the data access object for the table research.
// You can define custom methods on it to extend its functionality as needed.
type researchDao struct {
	*internal.ResearchDao
}

var (
	// Research is a globally accessible object for table research operations.
	Research = researchDao{internal.NewResearchDao()}
)

// Add your custom methods and functionality below.
