// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-18 21:09:17
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
	ConfigId    uint        `json:"configId"    description:"Parameter primary key"`
	ConfigName  string      `json:"configName"  description:"Parameter name"`
	ConfigKey   string      `json:"configKey"   description:"Parameter key name"`
	ConfigValue string      `json:"configValue" description:"Parameter key value"`
	ConfigType  int         `json:"configType"  description:"System built-in（Y is N is not）"`
	CreateBy    uint        `json:"createBy"    description:"Creator"`
	UpdateBy    uint        `json:"updateBy"    description:"Updater"`
	Remark      string      `json:"remark"      description:"Remark"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:"Creation time"`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:"Modification time"`
}
