// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-16 16:32:52
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictType is the golang structure for table sys_dict_type.
type SysDictType struct {
	DictId    uint64      `json:"dictId"    description:"Dictionary primary key"`
	DictName  string      `json:"dictName"  description:"Dictionary name"`
	DictType  string      `json:"dictType"  description:"Dictionary type"`
	Status    uint        `json:"status"    description:"Status（0normal 1disabled）"`
	CreateBy  uint        `json:"createBy"  description:"Creator"`
	UpdateBy  uint        `json:"updateBy"  description:"Updater"`
	Remark    string      `json:"remark"    description:"Remark"`
	CreatedAt *gtime.Time `json:"createdAt" description:"Creation date"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"Modification date"`
}
