// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-16 16:32:52
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData struct {
	DictCode  int64       `json:"dictCode"  description:"Dictionary encoding"`
	DictSort  int         `json:"dictSort"  description:"Dictionary sorting"`
	DictLabel string      `json:"dictLabel" description:"Dictionary label"`
	DictValue string      `json:"dictValue" description:"Dictionary key value"`
	DictType  string      `json:"dictType"  description:"Dictionary type"`
	CssClass  string      `json:"cssClass"  description:"Style attributes（other style extensions）"`
	ListClass string      `json:"listClass" description:"Table echo style"`
	IsDefault int         `json:"isDefault" description:"Whether it is default（1is 0is not）"`
	Status    int         `json:"status"    description:"Status（0normal 1disabled）"`
	CreateBy  uint64      `json:"createBy"  description:"Creator"`
	UpdateBy  uint64      `json:"updateBy"  description:"Updater"`
	Remark    string      `json:"remark"    description:"Remark"`
	CreatedAt *gtime.Time `json:"createdAt" description:"Creation time"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"Modification time"`
}
